### ISSUE TITLE
Links to, and content at, AMO

### ISSUE THREAD

**Issue by grahamperrin** [cliqz-oss/consentric#11]
https://github.com/cliqz-oss/re-consent/blob/master/README.md 

* refers to https://addons.mozilla.org/en-US/firefox/addon/re-consent/
* should refer to https://addons.mozilla.org/addon/re-consent/

https://cliqz.com/magazine/re-consent

* refers to https://addons.mozilla.org/de/firefox/addon/re-consent/
* should refer to https://addons.mozilla.org/addon/re-consent/

https://addons.mozilla.org/en-GB/firefox/addon/re-consent/

* is German
* should be English. 

https://cliqz.com/en/magazine/re-consent refers to https://addons.mozilla.org/addon/re-consent/ – is OK.

**Comment by sammacbeth** [comment]
Thanks for the report. I've updated the readme, and store listings should be updated today.
